### ISSUE TITLE
Toolbox is not up to date

### ISSUE THREAD

**Issue by decebal** [healthiers/express-graphiql-toolbox#1]
There are several bugs fixed on [toolbox](https://github.com/OlegIlyenko/graphql-toolbox) but are not reflected in this app, my guess is since you switched to loading it from cdn version.

one issue would be: https://github.com/OlegIlyenko/graphql-toolbox/issues/10

**Comment by bali182** [comment]
Hello @decebal, sorry for the late answer! I'm not planning to use anything different from the CDN. Will check it though maybe there were changes on how it's published.
